---
name: Pre-commit

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    uses: Baker-scripts/.github/.github/workflows/pre-commit.yml@af71b62edc8f3b7abde8a82936a32a051abd5c36 # main
