---
name: Pre-commit

"on":
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  pre-commit:
    uses: Baker-scripts/.github/.github/workflows/pre-commit.yml@01c10a0300ddea9ce38a5fb207306c85fa119998 # main
