---
name: Yaml Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v6
      - name: yamllint version
        run: |
          yamllint --version
      - name: yamllint run
        run: |
          shopt -s nullglob
          for f in ./*.yml; do
            echo "$f"
            yamllint "$f" --format github
          done
